language: python
python: 2.7
dist: trusty
before_install: []
install:
- pip install Sphinx sphinx_rtd_theme
- pip install -r requirements-docs.txt
before_script: []
script: sphinx-build -b html db/docs/source db/docs
after_script: []
